name: Resume CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tooling
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pandoc codespell texlive-latex-base
        version: latest

    - name: Build PDF
      run: make pdf

    - name: Save PDF resume
      uses: actions/upload-artifact@v3
      with:
        name: resume-pdf
        path: build/peterwhelan.pdf
